### ISSUE TITLE
Java error opening picker via Android (Expo)

### ISSUE THREAD

**Issue by Codeshark-NET** [Bur0/react-native-actions-sheet-picker#1]
Hey there!

First of all, thanks for creating this, it looks super awesome and brings all the features I'd be looking for prior. 🎖️

I was trying this out in the app I'm building, using Expo managed workflow (Expo SDK 45) and the example in the repo, but unfortunately it crashes once the action sheet is opened on Android (works fine on Web). 

`java.lang.Double cannot be cast to java.lang.Boolean`
![error](https://user-images.githubusercontent.com/5020508/169847775-a2fef757-5c8a-4d7b-a6a3-25a086887945.jpg)

I tried testing out the `react-native-actions-sheet` package too, to eliminate any dependency problem, and that seems to work without issue. 

I'm happy to help out adapting towards this, but am unable to give you further details than this for now, any idea? Thanks for your work! 🙌

**Comment by Bur0** [comment]
@Codeshark-NET Thank you for using it first and giving feedback. I will deal with the problem immediately.

**Comment by Codeshark-NET** [comment]
Hey there @Bur0! Great! I'm not near my computer currently, but I just copied the example from the readme, nothing additional. 👍

**Comment by StefanMeijer** [comment]
I have the same problem.. Any fix yet?

**Comment by Bur0** [comment]
Hi, first of all, sorry for the late reply, I think I found the problem. Can you try?

`expo install react-native-gesture-handler.`

**Comment by StefanMeijer** [comment]
> 

I would then get the error "Tried to register two views with the same name RNGestureHandlerButton" beacuse react-native-gesture-handler already exists in Expo and Expo is getting confused about where to get its information from, using react-navigation.

**Comment by Bur0** [comment]
I solved the problem by downgrading the gesture handler version.

If you can check then close the request?

**Comment by StefanMeijer** [comment]
> 

To what version?

**Comment by StefanMeijer** [comment]
> I solved the problem by downgrading the gesture handler version.
> 
> If you can check then close the request?

Thanks, this worked.

**Comment by tilted-tm** [comment]
Hi @Bur0 I have this issue (and don't use expo, i use `npx react-native init`) can you tell me what is the version of `react-native-gesture-handler` we need to downgrade to please? 🙂

**Comment by Bur0** [comment]
Hi @tilted-tm rCan you try to remove react-native-gesture-handler ? Because compatible version  is installed with the package.

**Comment by tilted-tm** [comment]
Thanks for the quick reply! Unfortunately I'm also using `react-native-gesture-handler` on the rest of my app but I downgraded the version to `2.1.1` (this package version) and am about to test it, I'll keep you updated if it works for me thanks! 🙂

**Comment by tilted-tm** [comment]
Alright so I can confirm that downgrading `react-native-gesture-handler` to `2.2.1` fixes the issue! Thanks for your help! 🙂

**Comment by tahaipek** [comment]
I have shared here the solution that worked without downgrading the package version. I am adding the link here as it may be an additional solution for the developers who encounter the error.

[#5 ](https://github.com/Bur0/react-native-actions-sheet-picker/issues/5#issuecomment-1228592482)
