### ISSUE TITLE
Java.lang.Boolean cannot be cast too Java.lang.Double

### ISSUE THREAD

**Issue by noelzappy** [Bur0/react-native-actions-sheet-picker#5]
The picker works fine on iOS however, on Android it throws the error `Java.lang.Boolean cannot be cast too Java.lang.Double`. 

![Screenshot_1656164045](https://user-images.githubusercontent.com/38583057/175775882-2cad2f73-36c5-4a9d-add0-a2210f00e697.png)

**Comment by StefanMeijer** [comment]
https://github.com/Bur0/react-native-actions-sheet-picker/issues/1

**Comment by noelzappy** [comment]
> #1
> 
> Downgrade gesture handler version.

To what version specifically?

**Comment by StefanMeijer** [comment]
> > #1
> 
> > 
> 
> > Downgrade gesture handler version.
> 
> 
> 
> To what version specifically?

I got mine working on: ~2.2.1

**Comment by AlixH** [comment]
Is downgrading the only solution ?

**Comment by tahaipek** [comment]
I think a downgrade is not the only solution. I solved it as below and it worked.

You can check the versions of the dependencies as follows.

`
npm why react-native-gesture-handler
`

As a result of running this command, I have reached the following rows.

```
react-native-gesture-handler@2.6.0
node_modules/react-native-gesture-handler
---react-native-gesture-handler@"^2.4.2" from the root project
---peer react-native-gesture-handler@">= 1.0.0" from @react-navigation/stack@6.2.3
---node_modules/@react-navigation/stack
------@react-navigation/stack@"^6.2.1" from the root project

react-native-gesture-handler@2.2.1
node_modules/react-native-actions-sheet-picker/node_modules/react-native-gesture-handler
---react-native-gesture-handler@"2.2.1" from react-native-actions-sheet-picker@0.3.5
---node_modules/react-native-actions-sheet-picker
------react-native-actions-sheet-picker@"^0.3.5" from the root project
```

I solved it by adding the following lines to "package.json" file.
```
"overrides": {
     "react-native-gesture-handler": "^2.6.0"
}
```

If you are using "yarn" you should add the following lines.

```
"resolutions": {
  "react-native-gesture-handler": <Gesture Handler version>
}
```

You can find more information on the website.
["Multiple versions of Gesture Handler were detected" documentation](https://docs.swmansion.com/react-native-gesture-handler/docs/troubleshooting/#multiple-versions-of-gesture-handler-were-detected)

**Comment by edsonjuniornarvaes** [comment]
> Eu acho que um rebaixamento não é a única solução. Eu resolvi como abaixo e funcionou.
> 
> Você pode verificar as versões das dependências da seguinte maneira.
> 
> `npm why react-native-gesture-handler`
> 
> Como resultado da execução deste comando, cheguei às seguintes linhas.
> 
> ```
> react-native-gesture-handler@2.6.0
> node_modules/react-native-gesture-handler
> ---react-native-gesture-handler@"^2.4.2" from the root project
> ---peer react-native-gesture-handler@">= 1.0.0" from @react-navigation/stack@6.2.3
> ---node_modules/@react-navigation/stack
> ------@react-navigation/stack@"^6.2.1" from the root project
> 
> react-native-gesture-handler@2.2.1
> node_modules/react-native-actions-sheet-picker/node_modules/react-native-gesture-handler
> ---react-native-gesture-handler@"2.2.1" from react-native-actions-sheet-picker@0.3.5
> ---node_modules/react-native-actions-sheet-picker
> ------react-native-actions-sheet-picker@"^0.3.5" from the root project
> ```
> 
> Resolvi-o adicionando as seguintes linhas ao arquivo "package.json.
> 
> ```
> "overrides": {
>      "react-native-gesture-handler": "^2.6.0"
> }
> ```
> 
> Se você estiver usando "fios", adicione as seguintes linhas.
> 
> ```
> "resolutions": {
>   "react-native-gesture-handler": <Gesture Handler version>
> }
> ```
> 
> Você pode encontrar mais informações no site. ["Documentação "Versões múltiplas do Gesture Handler foram detectadas"](https://docs.swmansion.com/react-native-gesture-handler/docs/troubleshooting/#multiple-versions-of-gesture-handler-were-detected)

Thank you, it worked for me
