### ISSUE TITLE
java.lang.Boolean cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by sadidarhamar** [Bur0/react-native-actions-sheet-picker#6]
i have completely new project created with npx react-native init, and i install react-native-actions-sheet-picker alongside react-native-gesture-handler because it required then i copy pasted example codes on npm. after i run my project i got following error java.lang.Boolean cannot be cast to java.lang.Double but when i try it online in snack.expo.dev it works fine

**Comment by Bur0** [comment]
Hi, @sadidarhamar https://github.com/Bur0/react-native-actions-sheet-picker/issues?q=is%3Aissue+is%3Aclosed

**Comment by Bur0** [comment]
Hi @sadidarhamar Is the problem solved ?
